// Mock data based on real building data from admin.homii.app
// Budget calculation: ~€250 per component per year per VHE
// Budget progress: budgeted amount vs spent-to-date (March = ~20% through year)

export const buildings = [
  {
    id: "BLD-001",
    complex: "B. Toren Havend.",
    complexId: "GRC-2401",
    location: "Gorinchem",
    vhe: 26,
    components: 8,
    utilities: ["heat", "water", "electricity"],
    budgetTotal: 52000,
    budgetSpent: 11440,
    dataQuality: "good",
  },
  {
    id: "BLD-002",
    complex: "De Bogerd Flats",
    complexId: "GRC-2402",
    location: "Gorinchem",
    vhe: 86,
    components: 11,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 236500,
    budgetSpent: 49665,
    dataQuality: "good",
  },
  {
    id: "BLD-003",
    complex: "De Korenbloem",
    complexId: "GRC-2403",
    location: "Gorinchem",
    vhe: 33,
    components: 7,
    utilities: ["heat", "water", "electricity"],
    budgetTotal: 57750,
    budgetSpent: 13860,
    dataQuality: "good",
  },
  {
    id: "BLD-004",
    complex: "De Lindeborg",
    complexId: "GRC-2404",
    location: "Gorinchem",
    vhe: 144,
    components: 12,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 432000,
    budgetSpent: 82080,
    dataQuality: "good",
  },
  {
    id: "BLD-005",
    complex: "De Vicaris",
    complexId: "GRC-2405",
    location: "Gorinchem",
    vhe: 16,
    components: 6,
    utilities: ["heat", "water"],
    budgetTotal: 24000,
    budgetSpent: 5520,
    dataQuality: "good",
  },
  {
    id: "BLD-006",
    complex: "Kennelweg 31-98",
    complexId: "GRC-2406",
    location: "Gorinchem",
    vhe: 30,
    components: 9,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 67500,
    budgetSpent: 14175,
    dataQuality: "good",
  },
  {
    id: "BLD-007",
    complex: "Kloostergang",
    complexId: "GRC-2407",
    location: "Gorinchem",
    vhe: 44,
    components: 10,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 110000,
    budgetSpent: 25300,
    dataQuality: "good",
  },
  {
    id: "BLD-008",
    complex: "Kop van de IJsbaan",
    complexId: "GRC-2408",
    location: "Gorinchem",
    vhe: 65,
    components: 13,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 211250,
    budgetSpent: 48588,
    dataQuality: "good",
  },
  {
    id: "BLD-009",
    complex: "Munterflat",
    complexId: "GRC-2409",
    location: "Gorinchem",
    vhe: 96,
    components: 14,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 336000,
    budgetSpent: 77280,
    dataQuality: "good",
  },
  {
    id: "BLD-010",
    complex: "Schelluinsevliet A",
    complexId: "GRC-2410",
    location: "Gorinchem",
    vhe: 9,
    components: 5,
    utilities: ["heat", "water"],
    budgetTotal: 11250,
    budgetSpent: 2588,
    dataQuality: "good",
  },
  {
    id: "BLD-011",
    complex: "Schelluinsevliet B",
    complexId: "GRC-2411",
    location: "Gorinchem",
    vhe: 40,
    components: 9,
    utilities: ["heat", "water", "warmWater"],
    budgetTotal: 90000,
    budgetSpent: 19800,
    dataQuality: "good",
  },
  {
    id: "BLD-012",
    complex: "Tichelaarflat",
    complexId: "GRC-2412",
    location: "Gorinchem",
    vhe: 90,
    components: 12,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 270000,
    budgetSpent: 64800,
    dataQuality: "good",
  },
  {
    id: "BLD-013",
    complex: "Valkeniersweg 1-59",
    complexId: "GRC-2413",
    location: "Gorinchem",
    vhe: 30,
    components: 8,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 60000,
    budgetSpent: 12600,
    dataQuality: "good",
  },
  {
    id: "BLD-014",
    complex: "Valkeniersweg 109-155",
    complexId: "GRC-2414",
    location: "Gorinchem",
    vhe: 24,
    components: 7,
    utilities: ["heat", "water", "warmWater"],
    budgetTotal: 42000,
    budgetSpent: 9660,
    dataQuality: "good",
  },
  {
    id: "BLD-015",
    complex: "Valkeniersweg 157-191",
    complexId: "GRC-2415",
    location: "Gorinchem",
    vhe: 18,
    components: 6,
    utilities: ["heat", "water", "electricity"],
    budgetTotal: 27000,
    budgetSpent: 5670,
    dataQuality: "good",
  },
  {
    id: "BLD-016",
    complex: "Valkeniersweg 61-107",
    complexId: "GRC-2416",
    location: "Gorinchem",
    vhe: 24,
    components: 7,
    utilities: ["heat", "water", "warmWater"],
    budgetTotal: 42000,
    budgetSpent: 8820,
    dataQuality: "good",
  },
  {
    id: "BLD-017",
    complex: "VVE Frisoflat",
    complexId: "GRC-2417",
    location: "Gorinchem",
    vhe: 138,
    components: 14,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 483000,
    budgetSpent: 106260,
    dataQuality: "good",
  },
  {
    id: "BLD-018",
    complex: "Aanl.Won.Clara",
    complexId: "GRC-2418",
    location: "Gorinchem",
    vhe: 10,
    components: 5,
    utilities: ["heat", "water"],
    budgetTotal: 12500,
    budgetSpent: 3375,
    dataQuality: "warning",
  },
  {
    id: "BLD-019",
    complex: "de Blauwe Keizer",
    complexId: "GRC-2419",
    location: "Gorinchem",
    vhe: 25,
    components: 8,
    utilities: ["heat", "water", "warmWater"],
    budgetTotal: 50000,
    budgetSpent: 13500,
    dataQuality: "warning",
  },
  {
    id: "BLD-020",
    complex: "Piazzaflat",
    complexId: "GRC-2420",
    location: "Gorinchem",
    vhe: 135,
    components: 13,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 438750,
    budgetSpent: 114075,
    dataQuality: "error",
  },
  {
    id: "BLD-021",
    complex: "VVE Boogflat I",
    complexId: "GRC-2421",
    location: "Gorinchem",
    vhe: 71,
    components: 11,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 195250,
    budgetSpent: 54670,
    dataQuality: "error",
  },
];

// ── Services (Components) ──
// Based on Servicekosten Besluit regulation — component codes from ERP system
// Gathered from ledger pages across all buildings

export const serviceCategories = [
  { id: "energy",    label: { en: "Energy",          nl: "Energie" } },
  { id: "water",     label: { en: "Water",           nl: "Water" } },
  { id: "building",  label: { en: "Building",        nl: "Gebouw" } },
  { id: "exterior",  label: { en: "Exterior",        nl: "Buitenruimte" } },
  { id: "insurance", label: { en: "Insurance",       nl: "Verzekering" } },
];

export const services = [
  {
    id: "SVC-201",
    code: "201",
    name: { en: "Heating Costs", nl: "Stookkosten" },
    description: {
      en: "Central heating supply, gas delivery, metering services, and transport costs for heat distribution",
      nl: "Centrale verwarming, gaslevering, meetdiensten en transportkosten voor warmtedistributie",
    },
    category: "energy",
    regulation: "Servicekosten Besluit Art. 1",
    variable: true,
    metered: true,
    buildingCount: 12,
    suppliers: ["ENGIE Energie Nederland", "Techem Energy Services BV", "Joulz Meetbedrijf B.V.", "Stedin Netbeh BV"],
    avgCostPerVhe: 185,
    status: "active",
  },
  {
    id: "SVC-202",
    code: "202",
    name: { en: "Water", nl: "Water" },
    description: {
      en: "Communal water supply and distribution, including metering for shared consumption",
      nl: "Gemeenschappelijk waterverbruik en distributie, inclusief meetdiensten voor gedeeld verbruik",
    },
    category: "water",
    regulation: "Servicekosten Besluit Art. 1",
    variable: true,
    metered: true,
    buildingCount: 16,
    suppliers: ["Oasen"],
    avgCostPerVhe: 45,
    status: "active",
  },
  {
    id: "SVC-204",
    code: "204",
    name: { en: "Communal Electricity", nl: "Gemeenschappelijke elektra" },
    description: {
      en: "Electricity for shared spaces: hallways, stairwells, elevators, parking garages, and outdoor lighting",
      nl: "Elektriciteit voor gemeenschappelijke ruimten: gangen, trappenhuizen, liften, parkeergarages en buitenverlichting",
    },
    category: "energy",
    regulation: "Servicekosten Besluit Art. 1",
    variable: false,
    metered: true,
    buildingCount: 21,
    suppliers: ["ENGIE Energie Nederland"],
    avgCostPerVhe: 65,
    status: "active",
  },
  {
    id: "SVC-212",
    code: "212",
    name: { en: "Common Interior Costs", nl: "Kosten algemene binnenruimte" },
    description: {
      en: "Maintenance and upkeep of shared interior spaces: lobbies, corridors, laundry rooms, and communal areas",
      nl: "Onderhoud en beheer van gemeenschappelijke binnenruimten: entrees, gangen, wasruimten en gemeenschappelijke ruimten",
    },
    category: "building",
    regulation: "Servicekosten Besluit Art. 1",
    variable: false,
    metered: false,
    buildingCount: 1,
    suppliers: [],
    avgCostPerVhe: 30,
    status: "active",
  },
  {
    id: "SVC-214",
    code: "214",
    name: { en: "Cleaning", nl: "Schoonmaak" },
    description: {
      en: "Regular cleaning of shared spaces: hallways, stairwells, elevators, windows of common areas, and entrance halls",
      nl: "Reguliere schoonmaak van gemeenschappelijke ruimten: gangen, trappenhuizen, liften, ramen van gemeenschappelijke ruimten en entrees",
    },
    category: "building",
    regulation: "Servicekosten Besluit Art. 1",
    variable: false,
    metered: false,
    buildingCount: 19,
    suppliers: [],
    avgCostPerVhe: 55,
    status: "active",
  },
  {
    id: "SVC-215",
    code: "215",
    name: { en: "Window Cleaning", nl: "Glasbewassing" },
    description: {
      en: "Professional exterior window cleaning for building facades and communal glass surfaces",
      nl: "Professionele glasbewassing van gevels en gemeenschappelijke glasoppervlakken",
    },
    category: "building",
    regulation: "Servicekosten Besluit Art. 1",
    variable: false,
    metered: false,
    buildingCount: 1,
    suppliers: [],
    avgCostPerVhe: 25,
    status: "active",
  },
  {
    id: "SVC-216",
    code: "216",
    name: { en: "Caretaker", nl: "Huismeester" },
    description: {
      en: "On-site caretaker services: building supervision, minor repairs, resident assistance, and facility management",
      nl: "Huismeesterdiensten: gebouwbeheer, kleine reparaties, bewonersondersteuning en facilitair beheer",
    },
    category: "building",
    regulation: "Servicekosten Besluit Art. 1",
    variable: false,
    metered: false,
    buildingCount: 1,
    suppliers: [],
    avgCostPerVhe: 120,
    status: "active",
  },
  {
    id: "SVC-217",
    code: "217",
    name: { en: "District Management", nl: "Wijkbeheer" },
    description: {
      en: "Neighbourhood and district management services: communal area supervision, tenant liaison, and area coordination",
      nl: "Wijkbeheer en buurtcoördinatie: toezicht gemeenschappelijke ruimten, bewonerscontact en gebiedscoördinatie",
    },
    category: "exterior",
    regulation: "Servicekosten Besluit Art. 1",
    variable: false,
    metered: false,
    buildingCount: 17,
    suppliers: [],
    avgCostPerVhe: 40,
    status: "active",
  },
  {
    id: "SVC-218",
    code: "218",
    name: { en: "Landscaping", nl: "Groenvoorziening" },
    description: {
      en: "Maintenance of gardens, lawns, hedges, trees, and green areas surrounding the building complex",
      nl: "Onderhoud van tuinen, gazons, hagen, bomen en groenvoorzieningen rondom het gebouwcomplex",
    },
    category: "exterior",
    regulation: "Servicekosten Besluit Art. 1",
    variable: false,
    metered: false,
    buildingCount: 8,
    suppliers: [],
    avgCostPerVhe: 50,
    status: "active",
  },
  {
    id: "SVC-220",
    code: "220",
    name: { en: "Glass Insurance (VvE)", nl: "Glasverzekering VvE" },
    description: {
      en: "Collective glass breakage insurance for the owners' association covering all communal and private glass surfaces",
      nl: "Collectieve glasbrakverzekering voor de VvE, dekkend alle gemeenschappelijke en privé glasoppervlakken",
    },
    category: "insurance",
    regulation: "Servicekosten Besluit Art. 1",
    variable: false,
    metered: false,
    buildingCount: 1,
    suppliers: [],
    avgCostPerVhe: 15,
    status: "active",
  },
  {
    id: "SVC-256",
    code: "256",
    name: { en: "Individual Water", nl: "Water Individueel" },
    description: {
      en: "Individual water metering and billing per housing unit, with separate consumption tracking",
      nl: "Individueel waterverbruik per wooneenheid, met afzonderlijke verbruiksregistratie",
    },
    category: "water",
    regulation: "Servicekosten Besluit Art. 1",
    variable: true,
    metered: true,
    buildingCount: 2,
    suppliers: ["Oasen"],
    avgCostPerVhe: 35,
    status: "active",
  },
];

// Getter functions
export function getBuilding(id) {
  return buildings.find((b) => b.id === id);
}

export function getBuildingByComplexId(complexId) {
  return buildings.find((b) => b.complexId === complexId);
}

export function getService(id) {
  return services.find((s) => s.id === id);
}

export function getServiceByCode(code) {
  return services.find((s) => s.code === code);
}
