// Mock data based on real building data from admin.homii.app
// Budget calculation: ~€250 per component per year per VHE
// Budget progress: budgeted amount vs spent-to-date (March = ~20% through year)

export const buildings = [
  {
    id: "BLD-001",
    complex: "B. Toren Havend.",
    complexId: "GRC-2401",
    location: "Gorinchem",
    vhe: 26,
    components: 8,
    utilities: ["heat", "water", "electricity"],
    budgetTotal: 52000,
    budgetSpent: 11440,
    dataQuality: "good",
  },
  {
    id: "BLD-002",
    complex: "De Bogerd Flats",
    complexId: "GRC-2402",
    location: "Gorinchem",
    vhe: 86,
    components: 11,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 236500,
    budgetSpent: 49665,
    dataQuality: "good",
  },
  {
    id: "BLD-003",
    complex: "De Korenbloem",
    complexId: "GRC-2403",
    location: "Gorinchem",
    vhe: 33,
    components: 7,
    utilities: ["heat", "water", "electricity"],
    budgetTotal: 57750,
    budgetSpent: 13860,
    dataQuality: "good",
  },
  {
    id: "BLD-004",
    complex: "De Lindeborg",
    complexId: "GRC-2404",
    location: "Gorinchem",
    vhe: 144,
    components: 12,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 432000,
    budgetSpent: 82080,
    dataQuality: "good",
  },
  {
    id: "BLD-005",
    complex: "De Vicaris",
    complexId: "GRC-2405",
    location: "Gorinchem",
    vhe: 16,
    components: 6,
    utilities: ["heat", "water"],
    budgetTotal: 24000,
    budgetSpent: 5520,
    dataQuality: "good",
  },
  {
    id: "BLD-006",
    complex: "Kennelweg 31-98",
    complexId: "GRC-2406",
    location: "Gorinchem",
    vhe: 30,
    components: 9,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 67500,
    budgetSpent: 14175,
    dataQuality: "good",
  },
  {
    id: "BLD-007",
    complex: "Kloostergang",
    complexId: "GRC-2407",
    location: "Gorinchem",
    vhe: 44,
    components: 10,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 110000,
    budgetSpent: 25300,
    dataQuality: "good",
  },
  {
    id: "BLD-008",
    complex: "Kop van de IJsbaan",
    complexId: "GRC-2408",
    location: "Gorinchem",
    vhe: 65,
    components: 13,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 211250,
    budgetSpent: 48588,
    dataQuality: "good",
  },
  {
    id: "BLD-009",
    complex: "Munterflat",
    complexId: "GRC-2409",
    location: "Gorinchem",
    vhe: 96,
    components: 14,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 336000,
    budgetSpent: 77280,
    dataQuality: "good",
  },
  {
    id: "BLD-010",
    complex: "Schelluinsevliet A",
    complexId: "GRC-2410",
    location: "Gorinchem",
    vhe: 9,
    components: 5,
    utilities: ["heat", "water"],
    budgetTotal: 11250,
    budgetSpent: 2588,
    dataQuality: "good",
  },
  {
    id: "BLD-011",
    complex: "Schelluinsevliet B",
    complexId: "GRC-2411",
    location: "Gorinchem",
    vhe: 40,
    components: 9,
    utilities: ["heat", "water", "warmWater"],
    budgetTotal: 90000,
    budgetSpent: 19800,
    dataQuality: "good",
  },
  {
    id: "BLD-012",
    complex: "Tichelaarflat",
    complexId: "GRC-2412",
    location: "Gorinchem",
    vhe: 90,
    components: 12,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 270000,
    budgetSpent: 64800,
    dataQuality: "good",
  },
  {
    id: "BLD-013",
    complex: "Valkeniersweg 1-59",
    complexId: "GRC-2413",
    location: "Gorinchem",
    vhe: 30,
    components: 8,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 60000,
    budgetSpent: 12600,
    dataQuality: "good",
  },
  {
    id: "BLD-014",
    complex: "Valkeniersweg 109-155",
    complexId: "GRC-2414",
    location: "Gorinchem",
    vhe: 24,
    components: 7,
    utilities: ["heat", "water", "warmWater"],
    budgetTotal: 42000,
    budgetSpent: 9660,
    dataQuality: "good",
  },
  {
    id: "BLD-015",
    complex: "Valkeniersweg 157-191",
    complexId: "GRC-2415",
    location: "Gorinchem",
    vhe: 18,
    components: 6,
    utilities: ["heat", "water", "electricity"],
    budgetTotal: 27000,
    budgetSpent: 5670,
    dataQuality: "good",
  },
  {
    id: "BLD-016",
    complex: "Valkeniersweg 61-107",
    complexId: "GRC-2416",
    location: "Gorinchem",
    vhe: 24,
    components: 7,
    utilities: ["heat", "water", "warmWater"],
    budgetTotal: 42000,
    budgetSpent: 8820,
    dataQuality: "good",
  },
  {
    id: "BLD-017",
    complex: "VVE Frisoflat",
    complexId: "GRC-2417",
    location: "Gorinchem",
    vhe: 138,
    components: 14,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 483000,
    budgetSpent: 106260,
    dataQuality: "good",
  },
  {
    id: "BLD-018",
    complex: "Aanl.Won.Clara",
    complexId: "GRC-2418",
    location: "Gorinchem",
    vhe: 10,
    components: 5,
    utilities: ["heat", "water"],
    budgetTotal: 12500,
    budgetSpent: 3375,
    dataQuality: "warning",
  },
  {
    id: "BLD-019",
    complex: "de Blauwe Keizer",
    complexId: "GRC-2419",
    location: "Gorinchem",
    vhe: 25,
    components: 8,
    utilities: ["heat", "water", "warmWater"],
    budgetTotal: 50000,
    budgetSpent: 13500,
    dataQuality: "warning",
  },
  {
    id: "BLD-020",
    complex: "Piazzaflat",
    complexId: "GRC-2420",
    location: "Gorinchem",
    vhe: 135,
    components: 13,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 438750,
    budgetSpent: 114075,
    dataQuality: "error",
  },
  {
    id: "BLD-021",
    complex: "VVE Boogflat I",
    complexId: "GRC-2421",
    location: "Gorinchem",
    vhe: 71,
    components: 11,
    utilities: ["heat", "water", "warmWater", "electricity"],
    budgetTotal: 195250,
    budgetSpent: 54670,
    dataQuality: "error",
  },
];

// Getter functions
export function getBuilding(id) {
  return buildings.find((b) => b.id === id);
}

export function getBuildingByComplexId(complexId) {
  return buildings.find((b) => b.complexId === complexId);
}
